# Generated by Django 6.0.3 on 2026-03-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=5)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('badge_type', models.CharField(choices=[('organic', 'Organic'), ('seasonal', 'Seasonal'), ('heritage', 'Heritage'), ('fresh', 'Fresh')], default='fresh', max_length=10)),
                ('origin_location', models.CharField(blank=True, max_length=150)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('out_of_stock', 'Out of Stock'), ('flagged', 'Flagged')], default='active', max_length=15)),
                ('total_sales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.farmerprofile')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['category'], name='products_categor_4083ff_idx'), models.Index(fields=['farmer'], name='products_farmer__60012d_idx'), models.Index(fields=['status'], name='products_status_a30e64_idx')],
            },
        ),
    ]
